---
title: Le Blog du Marié
timezone: Europe/Paris
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
lang: fr-FR
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
permalink: ":title/"
baseurl: 
url: 
site-twitter: 
author: Le Blog du Marié
author-img: david-freeman.jpg
about-author: I am a web developer focusing on front-end development. Always hungry
  to keep learning.
social-twitter: 
social-facebook: 
social-github: 
social-linkedin: 
social-email: 
discus-identifier: 
analytics: 
markdown: kramdown
plugins:
- jekyll-sitemap
- jekyll-paginate
- jemoji
paginate: 10
paginate_path: "/page/:num"
exclude:
- node_modules
- gulpfile.js
- package.json
- yarn.lock
